title: Web freshie
author: Lucas Wang
email: hurricanew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  talk about new stuff in web/UI development
  
# style
theme: minima

# social links
twitter_username: mindworks2018 # DO NOT include the @ character, or else the build will fail!
github_username:  hurricanew # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
